"""Transcribed shipped Nexus control table (a full Nexus survey: 318 rows).

Pure data: one row per config key that a shipped Nexus control reads
or writes. min/max/step/enum are adopted EXACTLY as the QML declares
them (SliderRow values are normalized 0..1 by StyledSlider.qml:152,173).
Every row carries the file:line it was transcribed from.
"""

UI_RANGES = {
    "Colours.setIntensity (scheme intensity; stored in scheme.json via CLI, not Config)": {"control": 'SliderRow (enabled only when Colours.scheme === "dynamic")', "min": 0, "max": 1, "note": 'step: fraction of maxIntensity=2.0 (caelestia scheme set -i 0..2)', "page": 'Advanced colors', "file": 'shell/modules/nexus/pages/wallandstyle/AdvancedColorsPage.qml', "line": 140},
    "KrohnkiteConfig.screenGapBetween (kwinrc, not shell config)": {"control": 'StepperRow', "min": 0, "max": 80, "note": 'step: (default 1)', "page": 'Window Tiling', "file": 'shell/modules/nexus/pages/desktop/KrohnkitePage.qml', "line": 169},
    "KrohnkiteConfig.screenGapTop/Bottom/Left/Right (kwinrc)": {"control": 'StepperRow', "min": 0, "max": 80, "note": 'step: (default 1)', "page": 'Window Tiling', "file": 'shell/modules/nexus/pages/desktop/KrohnkitePage.qml', "line": 179},
    "ai.claudeAccountsJson / ai.activeClaudeAccount": {"control": 'account cards (JSON list)', "page": 'AI Assistant', "file": 'shell/modules/nexus/pages/AiSettingsPage.qml', "line": 323},
    "ai.enableClaude": {"control": 'ToggleRow', "page": 'AI Assistant', "file": 'shell/modules/nexus/pages/AiSettingsPage.qml', "line": 587},
    "ai.enableClaudeCode": {"control": 'ToggleRow', "page": 'AI Assistant', "file": 'shell/modules/nexus/pages/AiSettingsPage.qml', "line": 579},
    "ai.enableGemini": {"control": 'ToggleRow', "page": 'AI Assistant', "file": 'shell/modules/nexus/pages/AiSettingsPage.qml', "line": 607},
    "ai.enableOllama": {"control": 'ToggleRow', "page": 'AI Assistant', "file": 'shell/modules/nexus/pages/AiSettingsPage.qml', "line": 544},
    "ai.enableOpenai": {"control": 'ToggleRow', "page": 'AI Assistant', "file": 'shell/modules/nexus/pages/AiSettingsPage.qml', "line": 599},
    "ai.enableOpencode": {"control": 'ToggleRow', "page": 'AI Assistant', "file": 'shell/modules/nexus/pages/AiSettingsPage.qml', "line": 621},
    "ai.enableOpencodeGo": {"control": 'ToggleRow', "page": 'AI Assistant', "file": 'shell/modules/nexus/pages/AiSettingsPage.qml', "line": 628},
    "ai.enableOpenrouter": {"control": 'ToggleRow', "page": 'AI Assistant', "file": 'shell/modules/nexus/pages/AiSettingsPage.qml', "line": 614},
    "ai.showCaelestiaMode": {"control": 'ToggleRow', "page": 'Sidebar', "file": 'shell/modules/nexus/pages/panels/SidebarPanel.qml', "line": 75},
    "ai.showNews": {"control": 'ToggleRow', "page": 'Sidebar', "file": 'shell/modules/nexus/pages/panels/SidebarPanel.qml', "line": 66},
    "appearance.ambientColor": {"control": 'ToggleRow (enabled only when !Colours.light)', "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 158},
    "appearance.ambientOpacity": {"control": 'SliderRow', "min": 0, "max": 1, "note": 'step: wheel=services.audioIncrement (enabled: ambientColor && !Colours.light)', "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 167},
    "appearance.anim.durations.scale": {"control": 'StepperRow', "min": 0.25, "max": 4, "step": 0.05, "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 316},
    "appearance.blur": {"control": 'ToggleRow (enabled: transparency.enabled && !better_blur_dx)', "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 222},
    "appearance.blurMask": {"control": 'ToggleRow (enabled: transparency.enabled && blur)', "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 246},
    "appearance.deformScale": {"control": 'StepperRow', "min": 0, "max": 1.5, "step": 0.05, "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 357},
    "appearance.font.mono.family": {"control": 'FontCard (select-one card)', "enum": ["SF Mono", "CaskaydiaCove NF"], "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 375},
    "appearance.font.scale": {"control": 'StepperRow', "min": 0.5, "max": 2, "step": 0.05, "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 285},
    "appearance.font.{headline,title,body,label}.family": {"control": 'FontCard (select-one card)', "enum": ["SF Pro", "GoogleSansFlex"], "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 370},
    "appearance.islands": {"control": 'ToggleRow ("Islands")', "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 100},
    "appearance.padding.scale": {"control": 'StepperRow', "min": 0.5, "max": 2, "step": 0.05, "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 306},
    "appearance.pitchBlack": {"control": 'ToggleRow ("Bezel mode (Pitch black)")', "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 92},
    "appearance.rounding.scale": {"control": 'StepperRow', "min": 0.5, "max": 2.0, "step": 0.1, "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 118},
    "appearance.spacing.scale": {"control": 'StepperRow', "min": 0.5, "max": 2, "step": 0.05, "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 296},
    "appearance.transparency.base": {"control": 'SliderRow', "min": 0, "max": 1, "note": 'step: wheel=services.audioIncrement (normalized 0-1 slider)', "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 141},
    "appearance.transparency.enabled": {"control": 'ToggleRow (off also forces appearance.blur=false)', "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 128},
    "appearance.transparency.layers": {"control": 'SliderRow', "min": 0, "max": 1, "note": 'step: wheel=services.audioIncrement (normalized 0-1 slider)', "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 149},
    "audio.sounds.cameraClick": {"control": 'ToggleRow (enabled: audio.sounds.enabled)', "page": 'Sound effects', "file": 'shell/modules/nexus/pages/audio/SoundEffectsPage.qml', "line": 46},
    "audio.sounds.chargingStarted": {"control": 'ToggleRow (enabled: audio.sounds.enabled)', "page": 'Sound effects', "file": 'shell/modules/nexus/pages/audio/SoundEffectsPage.qml', "line": 66},
    "audio.sounds.disabledNotifApps": {"control": 'chips list (StyledInputField add/remove)', "page": 'Muted notification apps', "file": 'shell/modules/nexus/pages/audio/NotificationSilencingPage.qml', "line": 19},
    "audio.sounds.effectTick": {"control": 'ToggleRow (enabled: audio.sounds.enabled)', "page": 'Sound effects', "file": 'shell/modules/nexus/pages/audio/SoundEffectsPage.qml', "line": 54},
    "audio.sounds.enabled": {"control": 'ToggleRow', "page": 'Sound effects', "file": 'shell/modules/nexus/pages/audio/SoundEffectsPage.qml', "line": 24},
    "audio.sounds.lock": {"control": 'ToggleRow (enabled: audio.sounds.enabled)', "page": 'Sound effects', "file": 'shell/modules/nexus/pages/audio/SoundEffectsPage.qml', "line": 74},
    "audio.sounds.lowBattery": {"control": 'ToggleRow (enabled: audio.sounds.enabled)', "page": 'Sound effects', "file": 'shell/modules/nexus/pages/audio/SoundEffectsPage.qml', "line": 88},
    "audio.sounds.notificationVolume": {"control": 'SliderRow', "min": 0, "max": 1, "note": 'step: wheel=services.audioIncrement (enabled: audio.sounds.enabled)', "page": 'Toasts', "file": 'shell/modules/nexus/pages/services/ToastPreferencesPage.qml', "line": 80},
    "audio.sounds.screenRecord": {"control": 'ToggleRow (enabled: audio.sounds.enabled)', "page": 'Sound effects', "file": 'shell/modules/nexus/pages/audio/SoundEffectsPage.qml', "line": 95},
    "audio.sounds.sfxVolume": {"control": 'SliderRow', "min": 0, "max": 1, "note": 'step: wheel=services.audioIncrement (enabled: audio.sounds.enabled)', "page": 'Sound effects', "file": 'shell/modules/nexus/pages/audio/SoundEffectsPage.qml', "line": 31},
    "audio.sounds.unlock": {"control": 'ToggleRow (enabled: audio.sounds.enabled)', "page": 'Sound effects', "file": 'shell/modules/nexus/pages/audio/SoundEffectsPage.qml', "line": 81},
    "background.desktopClock.enabled": {"control": 'ToggleRow', "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 89},
    "background.desktopClock.invertColors": {"control": 'ToggleRow', "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 213},
    "background.desktopClock.position": {"control": 'SelectRow', "enum": ["top-left", "top-center", "top-right", "center", "bottom-left", "bottom-center", "bottom-right"], "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 197},
    "background.desktopClock.scale": {"control": 'StepperRow', "min": 0.5, "max": 3, "step": 0.1, "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 186},
    "background.desktopIconsEnabled": {"control": 'ToggleRow (enabled: wallpaperEnabled; resets per-screen overrides)', "page": 'Desktop & Tiling', "file": 'shell/modules/nexus/pages/DesktopPage.qml', "line": 40},
    "background.desktopLyrics.alignment": {"control": 'SelectRow', "enum": ["0=Left", "1=Center", "2=Right"], "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 294},
    "background.desktopLyrics.autoHide": {"control": 'ToggleRow (visible: desktopLyrics.enabled)', "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 131},
    "background.desktopLyrics.enabled": {"control": 'ToggleRow (off also resets desktopLyrics.autoHide)', "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 119},
    "background.desktopLyrics.invertColors": {"control": 'ToggleRow', "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 308},
    "background.desktopLyrics.position": {"control": 'SelectRow', "enum": ["top-left", "top-center", "top-right", "center", "bottom-left", "bottom-center", "bottom-right"], "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 278},
    "background.desktopLyrics.scale": {"control": 'StepperRow', "min": 0.5, "max": 3, "step": 0.1, "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 267},
    "background.desktopShapes.autoHide": {"control": 'ToggleRow (visible: desktopShapes.enabled)', "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 109},
    "background.desktopShapes.enabled": {"control": 'ToggleRow (off also resets desktopShapes.autoHide)', "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 97},
    "background.desktopShapes.position": {"control": 'SelectRow', "enum": ["top-left", "top-center", "top-right", "center", "bottom-left", "bottom-center", "bottom-right"], "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 241},
    "background.desktopShapes.scale": {"control": 'StepperRow', "min": 0.5, "max": 3, "step": 0.1, "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 230},
    "background.materialYouIconsEnabled": {"control": 'ToggleRow (enabled: wallpaperEnabled && desktopIconsEnabled)', "page": 'Desktop & Tiling', "file": 'shell/modules/nexus/pages/DesktopPage.qml', "line": 57},
    "background.materialYouIconsVibrant": {"control": 'ToggleRow (enabled: wallpaperEnabled && desktopIconsEnabled && materialYouIconsEnabled)', "page": 'Desktop & Tiling', "file": 'shell/modules/nexus/pages/DesktopPage.qml', "line": 74},
    "background.slideshowEnabled": {"control": 'ToggleRow (enabled: background.wallpaperEnabled)', "page": 'Slideshow & Order', "file": 'shell/modules/nexus/pages/wallandstyle/SlideshowAndOrderPage.qml', "line": 33},
    "background.slideshowInterval": {"control": 'SliderRow', "min": 0, "max": 1, "note": 'step: wheel=services.audioIncrement (fraction of 60 min; valueLabel = max(1, round(v*60)) min)', "page": 'Slideshow & Order', "file": 'shell/modules/nexus/pages/wallandstyle/SlideshowAndOrderPage.qml', "line": 43},
    "background.slideshowRandom": {"control": 'ToggleRow (enabled: background.wallpaperEnabled)', "page": 'Slideshow & Order', "file": 'shell/modules/nexus/pages/wallandstyle/SlideshowAndOrderPage.qml', "line": 54},
    "background.videoWallpaperMuteOnMedia": {"control": 'ToggleRow', "page": 'Video wallpapers', "file": 'shell/modules/nexus/pages/wallandstyle/VideoWallpapersPage.qml', "line": 61},
    "background.videoWallpaperPauseOnAllDisplays": {"control": 'ToggleRow', "page": 'Video wallpapers', "file": 'shell/modules/nexus/pages/wallandstyle/VideoWallpapersPage.qml', "line": 55},
    "background.videoWallpaperPauseOnFullscreen": {"control": 'ToggleRow (visible only on Hyprland)', "page": 'Video wallpapers', "file": 'shell/modules/nexus/pages/wallandstyle/VideoWallpapersPage.qml', "line": 41},
    "background.videoWallpaperPauseOnTiled": {"control": 'ToggleRow (visible only on Hyprland)', "page": 'Video wallpapers', "file": 'shell/modules/nexus/pages/wallandstyle/VideoWallpapersPage.qml', "line": 48},
    "background.videoWallpaperPaused": {"control": 'ToggleRow', "page": 'Video wallpapers', "file": 'shell/modules/nexus/pages/wallandstyle/VideoWallpapersPage.qml', "line": 28},
    "background.videoWallpaperSoundEnabled": {"control": 'ToggleRow', "page": 'Video wallpapers', "file": 'shell/modules/nexus/pages/wallandstyle/VideoWallpapersPage.qml', "line": 35},
    "background.visualiser.autoHide": {"control": 'ToggleRow (visible: visualiser.enabled)', "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 155},
    "background.visualiser.blur": {"control": 'ToggleRow', "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 325},
    "background.visualiser.enabled": {"control": 'ToggleRow (off also resets visualiser.autoHide)', "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 141},
    "background.visualiser.hideOnAllMonitors": {"control": 'ToggleRow (enabled: visualiser.autoHide; visible: visualiser.enabled)', "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 165},
    "background.visualiser.rounding": {"control": 'StepperRow', "min": 0, "max": 1, "step": 0.05, "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 333},
    "background.visualiser.spacing": {"control": 'StepperRow', "min": 0.5, "max": 3, "step": 0.1, "page": 'Desktop Addons', "file": 'shell/modules/nexus/pages/wallandstyle/DesktopAddonsPage.qml', "line": 343},
    "background.wallpaperEnabled": {"control": 'ToggleRow (inverted: "Show KDE Desktop" writes !checked; resets per-screen overrides)', "page": 'Desktop & Tiling', "file": 'shell/modules/nexus/pages/DesktopPage.qml', "line": 24},
    "background.wallpaperFillMode": {"control": 'SelectRow', "enum": ["Crop", "Fit", "Stretch (Image.PreserveAspectCrop/PreserveAspectFit/Stretch)"], "page": 'Wallpaper settings', "file": 'shell/modules/nexus/pages/wallandstyle/WallpaperSettingsPage.qml', "line": 49},
    "background.wallpaperRecolor": {"control": 'ToggleRow (enabled: background.wallpaperEnabled)', "page": 'Wallpaper settings', "file": 'shell/modules/nexus/pages/wallandstyle/WallpaperSettingsPage.qml', "line": 68},
    "background.wallpaperRecolorStrength": {"control": 'SliderRow', "min": 0, "max": 1, "note": 'step: wheel=services.audioIncrement (enabled: wallpaperRecolor && wallpaperEnabled)', "page": 'Wallpaper settings', "file": 'shell/modules/nexus/pages/wallandstyle/WallpaperSettingsPage.qml', "line": 85},
    "bar.clock.background": {"control": 'ToggleRow', "page": 'Clock', "file": 'shell/modules/nexus/pages/panels/taskbar/BarClock.qml', "line": 19},
    "bar.clock.showDate": {"control": 'ToggleRow', "page": 'Clock', "file": 'shell/modules/nexus/pages/panels/taskbar/BarClock.qml', "line": 26},
    "bar.clock.showIcon": {"control": 'ToggleRow', "page": 'Clock', "file": 'shell/modules/nexus/pages/panels/taskbar/BarClock.qml', "line": 32},
    "bar.clock.showSeconds": {"control": 'ToggleRow', "page": 'Clock', "file": 'shell/modules/nexus/pages/panels/taskbar/BarClock.qml', "line": 38},
    "bar.dock.currentDesktopOnly": {"control": 'ToggleRow', "page": 'Dock', "file": 'shell/modules/nexus/pages/panels/taskbar/BarDock.qml', "line": 83},
    "bar.dock.iconSize": {"control": 'StepperRow', "min": 20, "step": 2, "note": 'max: max(20, Tokens.sizes.bar.innerWidth)', "page": 'Dock', "file": 'shell/modules/nexus/pages/panels/taskbar/BarDock.qml', "line": 54},
    "bar.dock.previewOnDesktop": {"control": 'ToggleRow', "page": 'Dock', "file": 'shell/modules/nexus/pages/panels/taskbar/BarDock.qml', "line": 91},
    "bar.dock.recolourIcons": {"control": 'ToggleRow', "page": 'Dock', "file": 'shell/modules/nexus/pages/panels/taskbar/BarDock.qml', "line": 67},
    "bar.dock.showBadges": {"control": 'ToggleRow', "page": 'Dock', "file": 'shell/modules/nexus/pages/panels/taskbar/BarDock.qml', "line": 75},
    "bar.dodgeFocusedOnly": {"control": 'ToggleRow (enabled: bar.persistent && bar.dodgeWindows)', "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 83},
    "bar.dodgeWindows": {"control": 'ToggleRow (enabled: bar.persistent)', "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 75},
    "bar.dragThreshold": {"control": 'StepperRow', "min": 0, "max": 200, "step": 5, "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 107},
    "bar.entries (dock.enabled)": {"control": 'ToggleRow', "page": 'Dock', "file": 'shell/modules/nexus/pages/panels/taskbar/BarDock.qml', "line": 20},
    "bar.entries (greeter/activeWindow.enabled)": {"control": 'ToggleRow', "page": 'Greeter', "file": 'shell/modules/nexus/pages/panels/taskbar/BarGreeter.qml', "line": 66},
    "bar.entries (updateIndicator.enabled)": {"control": 'ToggleRow', "page": 'Update indicator', "file": 'shell/modules/nexus/pages/panels/taskbar/BarUpdates.qml', "line": 28},
    "bar.fontScaleOffset": {"control": 'StepperRow', "min": -1.0, "max": 1.0, "step": 0.05, "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 192},
    "bar.github.background": {"control": 'ToggleRow', "page": 'GitHub', "file": 'shell/modules/nexus/pages/panels/taskbar/BarGithub.qml', "line": 99},
    "bar.greeter.afternoonStart": {"control": 'StepperRow', "min": 0, "max": 23, "step": 1, "page": 'Greeter', "file": 'shell/modules/nexus/pages/panels/taskbar/BarGreeter.qml', "line": 228},
    "bar.greeter.compact": {"control": 'ToggleRow', "page": 'Greeter', "file": 'shell/modules/nexus/pages/panels/taskbar/BarGreeter.qml', "line": 97},
    "bar.greeter.eveningStart": {"control": 'StepperRow', "min": 0, "max": 23, "step": 1, "page": 'Greeter', "file": 'shell/modules/nexus/pages/panels/taskbar/BarGreeter.qml', "line": 273},
    "bar.greeter.inverted": {"control": 'ToggleRow', "page": 'Greeter', "file": 'shell/modules/nexus/pages/panels/taskbar/BarGreeter.qml', "line": 107},
    "bar.greeter.mode": {"control": 'SelectRow', "enum": ["timeOfDay", "slideshow"], "page": 'Greeter', "file": 'shell/modules/nexus/pages/panels/taskbar/BarGreeter.qml', "line": 141},
    "bar.greeter.morningStart": {"control": 'StepperRow', "min": 0, "max": 23, "step": 1, "page": 'Greeter', "file": 'shell/modules/nexus/pages/panels/taskbar/BarGreeter.qml', "line": 183},
    "bar.greeter.nightStart": {"control": 'StepperRow', "min": 0, "max": 23, "step": 1, "page": 'Greeter', "file": 'shell/modules/nexus/pages/panels/taskbar/BarGreeter.qml', "line": 318},
    "bar.greeter.showOnHover": {"control": 'ToggleRow', "page": 'Greeter', "file": 'shell/modules/nexus/pages/panels/taskbar/BarGreeter.qml', "line": 116},
    "bar.greeter.slideshowInterval": {"control": 'StepperRow', "min": 5, "max": 3600, "step": 5, "enum": [" (seconds)"], "page": 'Greeter', "file": 'shell/modules/nexus/pages/panels/taskbar/BarGreeter.qml', "line": 352},
    "bar.greeter.slideshowRandom": {"control": 'ToggleRow', "page": 'Greeter', "file": 'shell/modules/nexus/pages/panels/taskbar/BarGreeter.qml', "line": 367},
    "bar.livePreviews": {"control": 'ToggleRow', "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 178},
    "bar.perElementPreviewScale + bar.perElementFontScale": {"control": 'ToggleRow (master; sets both)', "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 24},
    "bar.persistent": {"control": 'ToggleRow', "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 67},
    "bar.popouts.greeter": {"control": 'ToggleRow', "page": 'Greeter', "file": 'shell/modules/nexus/pages/panels/taskbar/BarGreeter.qml', "line": 126},
    "bar.popouts.statusIcons": {"control": 'ToggleRow', "page": 'Status icons', "file": 'shell/modules/nexus/pages/panels/taskbar/BarStatusIcons.qml', "line": 101},
    "bar.popouts.tray": {"control": 'ToggleRow', "page": 'Tray', "file": 'shell/modules/nexus/pages/panels/taskbar/BarTray.qml', "line": 39},
    "bar.position": {"control": 'SelectRow', "enum": ["top", "bottom", "left", "right"], "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 91},
    "bar.previewFontScales.<same 12 ids>": {"control": 'DoubleStepperRow (font column)', "min": -1.0, "max": 1.0, "step": 0.05, "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 93},
    "bar.previewScale": {"control": 'StepperRow', "min": 0.5, "max": 1.6, "step": 0.05, "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 168},
    "bar.previewScaleWithBar": {"control": 'ToggleRow', "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 185},
    "bar.previewScales.audio": {"control": 'DoubleStepperRow', "min": -1.0, "max": 1.0, "step": 0.05, "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 100},
    "bar.previewScales.battery": {"control": 'DoubleStepperRow', "min": -1.0, "max": 1.0, "step": 0.05, "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 113},
    "bar.previewScales.bluetooth": {"control": 'DoubleStepperRow', "min": -1.0, "max": 1.0, "step": 0.05, "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 126},
    "bar.previewScales.dock": {"control": 'DoubleStepperRow', "min": -1.0, "max": 1.0, "step": 0.05, "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 139},
    "bar.previewScales.github": {"control": 'DoubleStepperRow', "min": -1.0, "max": 1.0, "step": 0.05, "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 152},
    "bar.previewScales.greeter": {"control": 'DoubleStepperRow', "min": -1.0, "max": 1.0, "step": 0.05, "enum": [" (also writes activeWindow)"], "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 81},
    "bar.previewScales.lockStatus": {"control": 'DoubleStepperRow', "min": -1.0, "max": 1.0, "step": 0.05, "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 165},
    "bar.previewScales.network": {"control": 'DoubleStepperRow', "min": -1.0, "max": 1.0, "step": 0.05, "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 178},
    "bar.previewScales.notifications": {"control": 'DoubleStepperRow', "min": -1.0, "max": 1.0, "step": 0.05, "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 191},
    "bar.previewScales.peripheralBattery": {"control": 'DoubleStepperRow', "min": -1.0, "max": 1.0, "step": 0.05, "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 204},
    "bar.previewScales.trayMenu": {"control": 'DoubleStepperRow', "min": -1.0, "max": 1.0, "step": 0.05, "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 217},
    "bar.previewScales.wirelessPassword": {"control": 'DoubleStepperRow', "min": -1.0, "max": 1.0, "step": 0.05, "page": 'Per-element scaling offsets', "file": 'shell/modules/nexus/pages/panels/taskbar/BarPreviewScales.qml', "line": 230},
    "bar.scale": {"control": 'StepperRow', "min": 0.6, "max": 1.6, "step": 0.05, "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 157},
    "bar.scrollActions.brightness": {"control": 'ToggleRow', "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 249},
    "bar.scrollActions.volume": {"control": 'ToggleRow', "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 242},
    "bar.scrollActions.workspaces": {"control": 'ToggleRow', "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 234},
    "bar.showOnHover": {"control": 'ToggleRow', "page": 'Taskbar', "file": 'shell/modules/nexus/pages/panels/TaskbarPanel.qml', "line": 100},
    "bar.status.showWifi": {"control": 'ToggleRow', "page": 'Status icons', "file": 'shell/modules/nexus/pages/panels/taskbar/BarStatusIcons.qml', "line": 88},
    "bar.statusIcons.values": {"control": 'ListEditor (ordered toggles)', "page": 'Status icons', "file": 'shell/modules/nexus/pages/panels/taskbar/BarStatusIcons.qml', "line": 47},
    "bar.tray.background": {"control": 'ToggleRow', "page": 'Tray', "file": 'shell/modules/nexus/pages/panels/taskbar/BarTray.qml', "line": 20},
    "bar.tray.compact": {"control": 'ToggleRow', "page": 'Tray', "file": 'shell/modules/nexus/pages/panels/taskbar/BarTray.qml', "line": 33},
    "bar.tray.recolour": {"control": 'ToggleRow', "page": 'Tray', "file": 'shell/modules/nexus/pages/panels/taskbar/BarTray.qml', "line": 27},
    "bar.workspaces.activeIndicator": {"control": 'ToggleRow', "page": 'Workspaces indicator', "file": 'shell/modules/nexus/pages/panels/taskbar/BarWorkspaces.qml', "line": 77},
    "bar.workspaces.activeTrail": {"control": 'ToggleRow', "page": 'Workspaces indicator', "file": 'shell/modules/nexus/pages/panels/taskbar/BarWorkspaces.qml', "line": 83},
    "bar.workspaces.displayType": {"control": 'SelectRow', "enum": ["Shapes", "Text (BarWorkspaceDisplay enum)"], "page": 'Workspaces indicator', "file": 'shell/modules/nexus/pages/panels/taskbar/BarWorkspaces.qml', "line": 95},
    "bar.workspaces.maxWindowIcons": {"control": 'StepperRow', "min": 0, "max": 20, "step": 1, "page": 'Workspaces indicator', "file": 'shell/modules/nexus/pages/panels/taskbar/BarWorkspaces.qml', "line": 126},
    "bar.workspaces.occupiedBg": {"control": 'ToggleRow', "page": 'Workspaces indicator', "file": 'shell/modules/nexus/pages/panels/taskbar/BarWorkspaces.qml', "line": 89},
    "bar.workspaces.perMonitor": {"control": 'ToggleRow', "page": 'Workspaces indicator', "file": 'shell/modules/nexus/pages/panels/taskbar/BarWorkspaces.qml', "line": 137},
    "bar.workspaces.showUnoccupied": {"control": 'ToggleRow', "page": 'Workspaces indicator', "file": 'shell/modules/nexus/pages/panels/taskbar/BarWorkspaces.qml', "line": 112},
    "bar.workspaces.showWindows": {"control": 'ToggleRow', "page": 'Workspaces indicator', "file": 'shell/modules/nexus/pages/panels/taskbar/BarWorkspaces.qml', "line": 104},
    "bar.workspaces.showWindowsOnSpecialWorkspaces": {"control": 'ToggleRow', "page": 'Workspaces indicator', "file": 'shell/modules/nexus/pages/panels/taskbar/BarWorkspaces.qml', "line": 120},
    "bar.workspaces.shown": {"control": 'StepperRow', "min": 1, "max": 20, "step": 1, "page": 'Workspaces indicator', "file": 'shell/modules/nexus/pages/panels/taskbar/BarWorkspaces.qml', "line": 53},
    "border.rounding": {"control": 'StepperRow', "min": 0, "max": 100, "step": 1, "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 336},
    "border.smoothing": {"control": 'StepperRow', "min": 0, "max": 100, "step": 1, "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 347},
    "border.thickness": {"control": 'StepperRow', "min": 0, "max": 50, "step": 1, "enum": [" (px)"], "page": 'Theme & Effects', "file": 'shell/modules/nexus/pages/wallandstyle/AppearancePage.qml', "line": 108},
    "dashboard.colorizeMediaGif": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 174},
    "dashboard.dragThreshold": {"control": 'StepperRow', "min": 0, "max": 200, "step": 5, "enum": [" (px)"], "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 269},
    "dashboard.enabled": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 94},
    "dashboard.hoverThickness": {"control": 'StepperRow', "min": 1, "max": 100, "step": 1, "enum": [" (px)"], "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 248},
    "dashboard.hoverWidth": {"control": 'StepperRow', "min": 10, "max": 100, "step": 5, "enum": [" (%)"], "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 259},
    "dashboard.mediaUpdateInterval": {"control": 'StepperRow', "min": 100, "max": 2000, "step": 50, "enum": [" (ms)"], "page": 'Services', "file": 'shell/modules/nexus/pages/ServicesPage.qml', "line": 89},
    "dashboard.performance.showBattery": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 205},
    "dashboard.performance.showCpu": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 218},
    "dashboard.performance.showGpu": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 212},
    "dashboard.performance.showMemory": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 224},
    "dashboard.performance.showNetwork": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 236},
    "dashboard.performance.showStorage": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 230},
    "dashboard.profilePicShape": {"control": 'SelectRow', "enum": ["-1 Random + Circle", "Square", "Pill", "Diamond", "ClamShell", "Pentagon", "Gem", "Cookie4/6/7/9/12Sided (MaterialShape)"], "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 109},
    "dashboard.resourceUpdateInterval": {"control": 'StepperRow', "min": 0.5, "max": 10, "step": 0.5, "enum": [" (seconds; stored in ms)"], "page": 'Services', "file": 'shell/modules/nexus/pages/ServicesPage.qml', "line": 100},
    "dashboard.showClockSeconds": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 128},
    "dashboard.showDashboard": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 141},
    "dashboard.showMedia": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 148},
    "dashboard.showOnHover": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 101},
    "dashboard.showPerformance": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 154},
    "dashboard.showTerminal": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 167},
    "dashboard.showWeather": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 160},
    "dashboard.useMediaShapes": {"control": 'ToggleRow', "page": 'Dashboard', "file": 'shell/modules/nexus/pages/panels/DashboardPanel.qml', "line": 182},
    "general.apps.explorer (list append)": {"control": 'TextFieldRow/other (file-explorer pinning)', "page": 'Updates', "file": 'shell/modules/nexus/pages/UpdatesPage.qml', "line": 733},
    "general.battery.criticalLevel": {"control": 'StepperRow', "min": 1, "max": 50, "step": 1, "enum": [" (%)"], "page": 'Power', "file": 'shell/modules/nexus/pages/PowerPage.qml', "line": 128},
    "general.checkUpdates": {"control": 'ToggleRow', "page": 'Update indicator', "file": 'shell/modules/nexus/pages/panels/taskbar/BarUpdates.qml', "line": 44},
    "general.idle.inhibitWhenAudio": {"control": 'ToggleRow', "page": 'Power', "file": 'shell/modules/nexus/pages/PowerPage.qml', "line": 109},
    "general.idle.inhibitWhenCharging": {"control": 'ToggleRow', "page": 'Power', "file": 'shell/modules/nexus/pages/PowerPage.qml', "line": 116},
    "general.idle.lockBeforeSleep": {"control": 'ToggleRow', "page": 'Power', "file": 'shell/modules/nexus/pages/PowerPage.qml', "line": 102},
    "general.idle.timeouts (suspend entry enabled)": {"control": 'ToggleRow (writes entry.enabled / inserts entry)', "page": 'Power', "file": 'shell/modules/nexus/pages/PowerPage.qml', "line": 78},
    "general.idle.timeouts (suspend timeout minutes)": {"control": 'StepperRow', "min": 1, "max": 180, "step": 1, "enum": [" (minutes; sanitized Math.max(1, Math.min(180)); stored in seconds)"], "page": 'Power', "file": 'shell/modules/nexus/pages/PowerPage.qml', "line": 86},
    "general.krohnkiteEnabled": {"control": 'ToggleRow (also installs/unloads Krohnkite kwin script)', "page": 'Window Tiling', "file": 'shell/modules/nexus/pages/desktop/KrohnkitePage.qml', "line": 75},
    "general.krohnkiteLastLayout": {"control": 'SelectRow', "enum": ["BTree", "Monocle", "Floating", "Quarter", "Spread", "Stacked", "Stair", "Columns", "ThreeColumn", "Spiral", "Tile"], "page": 'Window Tiling', "file": 'shell/modules/nexus/pages/desktop/KrohnkitePage.qml', "line": 115},
    "general.language": {"control": 'SelectRow', "enum": ["system + installed translation catalogues"], "page": 'Language & region', "file": 'shell/modules/nexus/pages/LanguageAndRegion.qml', "line": 132},
    "general.logo": {"control": 'ToggleRow (on when != ""; writes "" or "caelestia")', "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 37},
    "general.magicLampEnabled": {"control": 'ToggleRow (also writes kwinrc magiclampEnabled/squashEnabled)', "page": 'Desktop & Tiling', "file": 'shell/modules/nexus/pages/DesktopPage.qml', "line": 91},
    "launcher.clipboardMaxEntries": {"control": 'StepperRow', "min": 1, "max": 100, "step": 1, "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 193},
    "launcher.clipboardMaxEntries (utilities view)": {"control": 'StepperRow', "min": 1, "max": 2048, "step": 10, "page": 'Clipboard', "file": 'shell/modules/nexus/pages/utilities/ClipboardPage.qml', "line": 23},
    "launcher.confirmClearClipboard": {"control": 'ToggleRow', "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 204},
    "launcher.dragThreshold": {"control": 'StepperRow', "min": 0, "max": 200, "step": 5, "enum": [" (px)"], "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 177},
    "launcher.enableDangerousActions": {"control": 'ToggleRow', "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 225},
    "launcher.enabled": {"control": 'ToggleRow', "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 30},
    "launcher.hoverThickness": {"control": 'StepperRow', "min": 1, "max": 100, "step": 1, "enum": [" (px)"], "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 157},
    "launcher.hoverWidth": {"control": 'StepperRow', "min": 10, "max": 100, "step": 5, "enum": [" (% of edge)"], "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 167},
    "launcher.maxShown": {"control": 'StepperRow', "min": 1, "max": 20, "step": 1, "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 139},
    "launcher.maxWallpapers": {"control": 'StepperRow', "min": 1, "max": 30, "step": 1, "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 148},
    "launcher.showBrowseOnEmpty": {"control": 'ToggleRow', "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 124},
    "launcher.showOnHover": {"control": 'ToggleRow', "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 111},
    "launcher.showPowerMenu": {"control": 'ToggleRow', "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 132},
    "launcher.useFuzzy.actions": {"control": 'ToggleRow', "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 245},
    "launcher.useFuzzy.apps": {"control": 'ToggleRow', "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 238},
    "launcher.useFuzzy.schemes": {"control": 'ToggleRow', "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 251},
    "launcher.useFuzzy.variants": {"control": 'ToggleRow', "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 257},
    "launcher.useFuzzy.wallpapers": {"control": 'ToggleRow', "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 263},
    "launcher.vimKeybinds": {"control": 'ToggleRow', "page": 'Launcher', "file": 'shell/modules/nexus/pages/panels/LauncherPanel.qml', "line": 217},
    "lock.blurWallpaper": {"control": 'ToggleRow', "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 184},
    "lock.enableFprint": {"control": 'ToggleRow', "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 201},
    "lock.hideNotifs": {"control": 'ToggleRow', "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 280},
    "lock.lockOnStartup": {"control": 'ToggleRow', "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 269},
    "lock.maxFprintTries": {"control": 'SelectRow', "enum": ["1", "2", "3", "4", "5 attempts"], "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 213},
    "lock.profilePicShape": {"control": 'SelectRow', "enum": ["-1 Random + Circle", "Square", "Pill", "Diamond", "ClamShell", "Pentagon", "Gem", "Cookie4/6/7/9/12Sided (MaterialShape)"], "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 237},
    "lock.recolourLogo": {"control": 'ToggleRow', "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 291},
    "lock.rotateProfilePic": {"control": 'ToggleRow', "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 258},
    "lock.showHibernate": {"control": 'ToggleRow', "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 320},
    "lock.showLogout": {"control": 'ToggleRow', "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 342},
    "lock.showReboot": {"control": 'ToggleRow', "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 353},
    "lock.showShutdown": {"control": 'ToggleRow', "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 364},
    "lock.showSleep": {"control": 'ToggleRow', "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 308},
    "lock.showSwitchUser": {"control": 'ToggleRow', "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 331},
    "lock.syncWallpaper": {"control": 'ToggleRow', "page": 'Lock Screen', "file": 'shell/modules/nexus/pages/wallandstyle/LockScreenPage.qml', "line": 147},
    "nexus.networkRescanInterval": {"control": 'StepperRow', "min": 5, "max": 120, "step": 5, "enum": [" (seconds; stored in ms)"], "page": 'Services', "file": 'shell/modules/nexus/pages/ServicesPage.qml', "line": 110},
    "nexus.wallpapersPerRow": {"control": '(no control; read-only Repeater model)', "page": 'Wallpapers', "file": 'shell/modules/nexus/pages/wallandstyle/WallpaperSelect.qml', "line": 80},
    "notifs.actionOnClick": {"control": 'ToggleRow', "page": 'Notifications', "file": 'shell/modules/nexus/pages/services/NotificationPreferencesPage.qml', "line": 162},
    "notifs.clearThreshold": {"control": 'SliderRow', "min": 0, "max": 1, "note": 'step: wheel=services.audioIncrement (swipe fraction)', "page": 'Notifications', "file": 'shell/modules/nexus/pages/services/NotificationPreferencesPage.qml', "line": 190},
    "notifs.defaultExpireTimeout": {"control": 'StepperRow', "min": 1, "max": 60, "step": 1, "enum": [" (seconds; stored in ms)"], "page": 'Notifications', "file": 'shell/modules/nexus/pages/services/NotificationPreferencesPage.qml', "line": 117},
    "notifs.expandThreshold": {"control": 'StepperRow', "min": 5, "max": 100, "step": 5, "enum": [" (px)"], "page": 'Notifications', "file": 'shell/modules/nexus/pages/services/NotificationPreferencesPage.qml', "line": 170},
    "notifs.expire": {"control": 'ToggleRow', "page": 'Notifications', "file": 'shell/modules/nexus/pages/services/NotificationPreferencesPage.qml', "line": 103},
    "notifs.fullscreen": {"control": 'SelectRow', "enum": ["off", "on"], "page": 'Notifications', "file": 'shell/modules/nexus/pages/services/NotificationPreferencesPage.qml', "line": 78},
    "notifs.fullscreenExpireTimeout": {"control": 'StepperRow', "min": 1, "max": 30, "step": 1, "enum": [" (seconds; stored in ms)"], "page": 'Notifications', "file": 'shell/modules/nexus/pages/services/NotificationPreferencesPage.qml', "line": 180},
    "notifs.groupPreviewNum": {"control": 'StepperRow', "min": 1, "max": 10, "step": 1, "page": 'Notifications', "file": 'shell/modules/nexus/pages/services/NotificationPreferencesPage.qml', "line": 127},
    "notifs.maxNotifs": {"control": 'StepperRow', "min": 20, "max": 2000, "step": 50, "page": 'Notifications', "file": 'shell/modules/nexus/pages/services/NotificationPreferencesPage.qml', "line": 147},
    "notifs.maxPopups": {"control": 'StepperRow', "min": 0, "max": 30, "step": 1, "page": 'Notifications', "file": 'shell/modules/nexus/pages/services/NotificationPreferencesPage.qml', "line": 137},
    "notifs.monitor": {"control": 'SelectRow', "enum": ["all", "focused"], "page": 'Notifications', "file": 'shell/modules/nexus/pages/services/NotificationPreferencesPage.qml', "line": 87},
    "notifs.openExpanded": {"control": 'ToggleRow', "page": 'Notifications', "file": 'shell/modules/nexus/pages/services/NotificationPreferencesPage.qml', "line": 110},
    "notifs.position": {"control": 'SelectRow', "enum": ["auto", "top-left", "top-center", "top-right", "bottom-left", "bottom-center", "bottom-right"], "page": 'Notifications', "file": 'shell/modules/nexus/pages/services/NotificationPreferencesPage.qml', "line": 95},
    "osd.enableBrightness": {"control": 'ToggleRow', "page": 'On-screen sliders', "file": 'shell/modules/nexus/pages/utilities/OsdPage.qml', "line": 45},
    "osd.enableMicrophone": {"control": 'ToggleRow', "page": 'On-screen sliders', "file": 'shell/modules/nexus/pages/utilities/OsdPage.qml', "line": 38},
    "osd.enableVolume": {"control": 'ToggleRow', "page": 'On-screen sliders', "file": 'shell/modules/nexus/pages/utilities/OsdPage.qml', "line": 31},
    "osd.enabled": {"control": 'ToggleRow', "page": 'On-screen sliders', "file": 'shell/modules/nexus/pages/utilities/OsdPage.qml', "line": 23},
    "osd.hideDelay": {"control": 'StepperRow', "min": 1, "max": 10, "step": 1, "enum": [" (seconds; stored in ms)"], "page": 'On-screen sliders', "file": 'shell/modules/nexus/pages/utilities/OsdPage.qml', "line": 83},
    "osd.hoverThickness": {"control": 'StepperRow', "min": 1, "max": 100, "step": 1, "enum": [" (px)"], "page": 'On-screen sliders', "file": 'shell/modules/nexus/pages/utilities/OsdPage.qml', "line": 57},
    "osd.hoverWidth": {"control": 'StepperRow', "min": 10, "max": 100, "step": 5, "enum": [" (%)"], "page": 'On-screen sliders', "file": 'shell/modules/nexus/pages/utilities/OsdPage.qml', "line": 68},
    "overview.baseDuration": {"control": 'StepperRow', "min": 100, "max": 1000, "step": 50, "enum": [" (ms)"], "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 225},
    "overview.blobScaleSpeed": {"control": 'StepperRow', "min": 0.1, "max": 5.0, "step": 0.1, "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 234},
    "overview.disableWallpaperBlur": {"control": 'ToggleRow', "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 191},
    "overview.dragThreshold": {"control": 'StepperRow', "min": 10, "max": 200, "step": 5, "enum": [" (visible only when !showOnHover)"], "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 131},
    "overview.easingType": {"control": 'SelectRow', "enum": ["0 Linear", "2 QuadraticOut", "3 QuadraticInOut", "6 CubicOut", "10 QuarticOut", "14 QuinticOut", "18 SineOut", "22 ExponentialOut", "26 CircularOut", "30 ElasticOut", "33 BackIn", "34 BackOut", "38 BounceOut"], "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 207},
    "overview.enableOverviewBlur": {"control": 'ToggleRow', "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 197},
    "overview.enabled": {"control": 'ToggleRow', "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 108},
    "overview.gridFadeSpeed": {"control": 'StepperRow', "min": 0.1, "max": 5.0, "step": 0.1, "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 252},
    "overview.hoverBottomLeft": {"control": 'ToggleRow', "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 159},
    "overview.hoverBottomRight": {"control": 'ToggleRow', "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 164},
    "overview.hoverThickness": {"control": 'StepperRow', "min": 1, "max": 100, "step": 1, "enum": [" (visible only when showOnHover)"], "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 120},
    "overview.hoverTopLeft": {"control": 'ToggleRow', "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 148},
    "overview.hoverTopRight": {"control": 'ToggleRow', "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 154},
    "overview.layoutType": {"control": 'SelectRow', "enum": ["0=KDE Grid", "1=GNOME Grid"], "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 173},
    "overview.showOnHover": {"control": 'ToggleRow', "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 114},
    "overview.wallpaperFadeSpeed": {"control": 'StepperRow', "min": 0.1, "max": 5.0, "step": 0.1, "page": 'Overview', "file": 'shell/modules/nexus/pages/panels/OverviewPanel.qml', "line": 243},
    "services.arpcCaelestiaInfo": {"control": 'ToggleRow', "page": 'Discord Rich Presence', "file": 'shell/modules/nexus/pages/services/ArpcPage.qml', "line": 74},
    "services.arpcEnabled": {"control": 'ToggleRow', "page": 'Discord Rich Presence', "file": 'shell/modules/nexus/pages/services/ArpcPage.qml', "line": 56},
    "services.arpcIdleTimeout": {"control": 'StepperRow', "min": 0, "max": 60, "step": 1, "enum": [" (minutes; stored in seconds)"], "page": 'Discord Rich Presence', "file": 'shell/modules/nexus/pages/services/ArpcPage.qml', "line": 83},
    "services.arpcManualOverride": {"control": 'ToggleRow', "page": 'Discord Rich Presence', "file": 'shell/modules/nexus/pages/services/ArpcPage.qml', "line": 439},
    "services.arpcSteamAutoDetect": {"control": 'ToggleRow', "page": 'Discord Rich Presence', "file": 'shell/modules/nexus/pages/services/ArpcPage.qml', "line": 65},
    "services.audioIncrement": {"control": 'StepperRow', "min": 1, "max": 50, "step": 1, "enum": [" (% shown; stored as fraction v/100)"], "page": 'Services', "file": 'shell/modules/nexus/pages/ServicesPage.qml', "line": 151},
    "services.autoSchemeDarkTime": {"control": 'StepperRow (visible: autoSchemeEnabled && mode=="fixed")', "min": 0, "max": 23, "note": 'step: (hour; stored as "HH:MM" string)', "page": 'Advanced colors', "file": 'shell/modules/nexus/pages/wallandstyle/AdvancedColorsPage.qml', "line": 120},
    "services.autoSchemeEnabled": {"control": 'ToggleRow ("Automatic light and dark")', "page": 'Advanced colors', "file": 'shell/modules/nexus/pages/wallandstyle/AdvancedColorsPage.qml', "line": 89},
    "services.autoSchemeLightTime": {"control": 'StepperRow (visible: autoSchemeEnabled && mode=="fixed")', "min": 0, "max": 23, "note": 'step: (hour; stored as "HH:MM" string)', "page": 'Advanced colors', "file": 'shell/modules/nexus/pages/wallandstyle/AdvancedColorsPage.qml', "line": 109},
    "services.autoSchemeMode": {"control": 'SelectRow (visible: autoSchemeEnabled)', "enum": ["solar", "fixed"], "page": 'Advanced colors', "file": 'shell/modules/nexus/pages/wallandstyle/AdvancedColorsPage.qml', "line": 98},
    "services.brightnessIncrement": {"control": 'StepperRow', "min": 1, "max": 50, "step": 1, "enum": [" (% shown; stored as fraction v/100)"], "page": 'Services', "file": 'shell/modules/nexus/pages/ServicesPage.qml', "line": 162},
    "services.clockFormat": {"control": 'SelectRow', "enum": ["Auto", "12-hour", "24-hour (ClockFormat enum)"], "page": 'Language & region', "file": 'shell/modules/nexus/pages/LanguageAndRegion.qml', "line": 419},
    "services.dataUnits": {"control": 'SelectRow', "enum": ["Binary (KiB MiB)", "Decimal (KB MB) (DataUnit enum)"], "page": 'Language & region', "file": 'shell/modules/nexus/pages/LanguageAndRegion.qml', "line": 405},
    "services.defaultPlayer": {"control": 'SelectRow', "enum": ["(dynamic list of running players + Auto)"], "page": 'Services', "file": 'shell/modules/nexus/pages/ServicesPage.qml', "line": 135},
    "services.gpuType": {"control": 'SelectRow', "enum": ["(dynamic gpuValues list)"], "page": 'Services', "file": 'shell/modules/nexus/pages/ServicesPage.qml', "line": 206},
    "services.maxVolume": {"control": 'StepperRow', "min": 50, "max": 200, "step": 5, "enum": [" (% shown; stored as fraction v/100)"], "page": 'Services', "file": 'shell/modules/nexus/pages/ServicesPage.qml', "line": 172},
    "services.sensorUnits": {"control": 'SelectRow', "enum": ["Auto", "Celsius", "Fahrenheit", "Kelvin (TemperatureUnit enum)"], "page": 'Language & region', "file": 'shell/modules/nexus/pages/LanguageAndRegion.qml', "line": 397},
    "services.smartScheme": {"control": 'ToggleRow ("Smart color scheme")', "page": 'Advanced colors', "file": 'shell/modules/nexus/pages/wallandstyle/AdvancedColorsPage.qml', "line": 81},
    "services.visualiserBars": {"control": 'StepperRow', "min": 10, "max": 120, "step": 2, "page": 'Services', "file": 'shell/modules/nexus/pages/ServicesPage.qml', "line": 196},
    "services.weatherUnits": {"control": 'SelectRow', "enum": ["Auto", "Celsius", "Fahrenheit", "Kelvin (TemperatureUnit enum)"], "page": 'Language & region', "file": 'shell/modules/nexus/pages/LanguageAndRegion.qml', "line": 388},
    "session.commands.{logout,shutdown,hibernate,reboot}": {"control": 'LabeledField (free text command string; stored as list)', "page": 'Session', "file": 'shell/modules/nexus/pages/SessionPage.qml', "line": 100},
    "session.dragThreshold": {"control": 'StepperRow', "min": 10, "max": 200, "step": 5, "enum": [" (px)"], "page": 'Session', "file": 'shell/modules/nexus/pages/SessionPage.qml', "line": 53},
    "session.enabled": {"control": 'ToggleRow', "page": 'Session', "file": 'shell/modules/nexus/pages/SessionPage.qml', "line": 36},
    "session.icons.{logout,shutdown,hibernate,reboot}": {"control": 'LabeledField (free text Material icon name)', "page": 'Session', "file": 'shell/modules/nexus/pages/SessionPage.qml', "line": 69},
    "session.vimKeybinds": {"control": 'ToggleRow', "page": 'Session', "file": 'shell/modules/nexus/pages/SessionPage.qml', "line": 45},
    "sidebar.dragThreshold": {"control": 'StepperRow', "min": 0, "max": 200, "step": 5, "enum": [" (px)"], "page": 'Sidebar', "file": 'shell/modules/nexus/pages/panels/SidebarPanel.qml', "line": 36},
    "sidebar.enabled": {"control": 'ToggleRow', "page": 'Sidebar', "file": 'shell/modules/nexus/pages/panels/SidebarPanel.qml', "line": 29},
    "sidebar.grabWidth": {"control": 'StepperRow', "min": 1, "max": 100, "step": 1, "enum": [" (px)"], "page": 'Sidebar', "file": 'shell/modules/nexus/pages/panels/SidebarPanel.qml', "line": 48},
    "tabSwitch.allScreens": {"control": 'ToggleRow (also writes kwinrc TabBox MultiScreenMode)', "page": 'Window Switcher', "file": 'shell/modules/nexus/pages/panels/TabSwitcherPanel.qml', "line": 164},
    "tabSwitch.currentDesktopOnly": {"control": 'ToggleRow (also writes kwinrc TabBox DesktopMode)', "page": 'Window Switcher', "file": 'shell/modules/nexus/pages/panels/TabSwitcherPanel.qml', "line": 114},
    "tabSwitch.enabled": {"control": 'ToggleRow', "page": 'Window Switcher', "file": 'shell/modules/nexus/pages/panels/TabSwitcherPanel.qml', "line": 72},
    "tabSwitch.previewOnDesktop": {"control": 'ToggleRow (also writes kwinrc TabBox HighlightWindows)', "page": 'Window Switcher', "file": 'shell/modules/nexus/pages/panels/TabSwitcherPanel.qml', "line": 129},
    "tabSwitch.showMinimized": {"control": 'ToggleRow (also writes kwinrc TabBox MinMode)', "page": 'Window Switcher', "file": 'shell/modules/nexus/pages/panels/TabSwitcherPanel.qml', "line": 149},
    "utilities.dragThreshold": {"control": 'StepperRow', "min": 0, "max": 200, "step": 5, "enum": [" (px)"], "page": 'Quick toggle (panel)', "file": 'shell/modules/nexus/pages/panels/UtilitiesPanel.qml', "line": 68},
    "utilities.enabled": {"control": 'ToggleRow', "page": 'Quick toggle (panel)', "file": 'shell/modules/nexus/pages/panels/UtilitiesPanel.qml', "line": 29},
    "utilities.gameMode.autoEnable": {"control": 'ToggleRow', "page": 'Game mode', "file": 'shell/modules/nexus/pages/services/GameModePage.qml', "line": 35},
    "utilities.gameMode.disableDesktopLyrics": {"control": 'ToggleRow', "page": 'Game mode', "file": 'shell/modules/nexus/pages/services/GameModePage.qml', "line": 109},
    "utilities.gameMode.disableHyprlandAnimations": {"control": 'ToggleRow (visible only on Hyprland)', "page": 'Game mode', "file": 'shell/modules/nexus/pages/services/GameModePage.qml', "line": 60},
    "utilities.gameMode.disableHyprlandBlur": {"control": 'ToggleRow (visible only on Hyprland)', "page": 'Game mode', "file": 'shell/modules/nexus/pages/services/GameModePage.qml', "line": 67},
    "utilities.gameMode.disableHyprlandGaps": {"control": 'ToggleRow (visible only on Hyprland)', "page": 'Game mode', "file": 'shell/modules/nexus/pages/services/GameModePage.qml', "line": 73},
    "utilities.gameMode.disableHyprlandShadows": {"control": 'ToggleRow (visible only on Hyprland)', "page": 'Game mode', "file": 'shell/modules/nexus/pages/services/GameModePage.qml', "line": 79},
    "utilities.gameMode.disableShellTransparency": {"control": 'ToggleRow', "page": 'Game mode', "file": 'shell/modules/nexus/pages/services/GameModePage.qml', "line": 98},
    "utilities.gameMode.disableToastTransparency": {"control": 'ToggleRow', "page": 'Game mode', "file": 'shell/modules/nexus/pages/services/GameModePage.qml', "line": 104},
    "utilities.gameMode.disableVisualizer": {"control": 'ToggleRow', "page": 'Game mode', "file": 'shell/modules/nexus/pages/services/GameModePage.qml', "line": 114},
    "utilities.gameMode.disableWindowTransparency": {"control": 'ToggleRow (visible only on Hyprland)', "page": 'Game mode', "file": 'shell/modules/nexus/pages/services/GameModePage.qml', "line": 85},
    "utilities.hoverThickness": {"control": 'StepperRow', "min": 1, "max": 100, "step": 1, "enum": [" (px)"], "page": 'Quick toggle (panel)', "file": 'shell/modules/nexus/pages/panels/UtilitiesPanel.qml', "line": 44},
    "utilities.hoverWidth": {"control": 'StepperRow', "min": 10, "max": 100, "step": 5, "enum": [" (%)"], "page": 'Quick toggle (panel)', "file": 'shell/modules/nexus/pages/panels/UtilitiesPanel.qml', "line": 56},
    "utilities.maxToasts": {"control": 'StepperRow', "min": 1, "max": 10, "step": 1, "page": 'Toasts', "file": 'shell/modules/nexus/pages/services/ToastPreferencesPage.qml', "line": 50},
    "utilities.quickToggles[id].enabled": {"control": 'ToggleRow (per id: wifi|bluetooth|vpn|settings|colorpicker|wallpaper|badapple|mic|dnd|gameMode|pauseWallpaper|nightlight|easyeffects|restartShell)', "page": 'Quick toggles', "file": 'shell/modules/nexus/pages/utilities/QuickTogglesPage.qml', "line": 89},
    "utilities.showGifRecorder": {"control": 'ToggleRow', "page": 'Utilities panel', "file": 'shell/modules/nexus/pages/utilities/UtilitiesPanelPage.qml', "line": 38},
    "utilities.showKeepAwake": {"control": 'ToggleRow', "page": 'Utilities panel', "file": 'shell/modules/nexus/pages/utilities/UtilitiesPanelPage.qml', "line": 23},
    "utilities.showOnHover": {"control": 'ToggleRow', "page": 'Quick toggle (panel)', "file": 'shell/modules/nexus/pages/panels/UtilitiesPanel.qml', "line": 36},
    "utilities.showQuickToggles": {"control": 'ToggleRow', "page": 'Utilities panel', "file": 'shell/modules/nexus/pages/utilities/UtilitiesPanelPage.qml', "line": 45},
    "utilities.showScreenRecorder": {"control": 'ToggleRow', "page": 'Utilities panel', "file": 'shell/modules/nexus/pages/utilities/UtilitiesPanelPage.qml', "line": 31},
    "utilities.toasts.chargingChanged": {"control": 'ToggleRow', "page": 'Toast events', "file": 'shell/modules/nexus/pages/services/ToastEventsPage.qml', "line": 26},
    "utilities.toasts.configLoaded": {"control": 'ToggleRow', "page": 'Toast events', "file": 'shell/modules/nexus/pages/services/ToastEventsPage.qml', "line": 45},
    "utilities.toasts.fullscreen": {"control": 'SelectRow', "enum": ["off", "important", "all"], "page": 'Toasts', "file": 'shell/modules/nexus/pages/services/ToastPreferencesPage.qml', "line": 41},
    "utilities.toasts.gameModeChanged": {"control": 'ToggleRow', "page": 'Toast events', "file": 'shell/modules/nexus/pages/services/ToastEventsPage.qml', "line": 32},
    "utilities.toasts.nightLightChanged": {"control": 'ToggleRow', "page": 'Toast events', "file": 'shell/modules/nexus/pages/services/ToastEventsPage.qml', "line": 38},
    "utilities.toasts.transparency": {"control": 'ToggleRow', "page": 'Toasts', "file": 'shell/modules/nexus/pages/services/ToastPreferencesPage.qml', "line": 60},
    "utilities.toasts.transparencyBase": {"control": 'SliderRow', "min": 0, "max": 1, "note": 'step: wheel=services.audioIncrement (enabled: toasts.transparency)', "page": 'Toasts', "file": 'shell/modules/nexus/pages/services/ToastPreferencesPage.qml', "line": 67},
}
