"""assistant.settings.catalog — generated community docs (F23,
exponential-build-5).

The registry is generated from the upstream checkout (gen_adapter), and
anything HAND-written about 272 tools drifts the moment upstream moves
(the A0 recon found exactly that: five tools removed upstream while
prose still described them). This module extends the gen_adapter
pattern — GENERATE, never hand-write, verify byte-identity — to the two
community-facing artifacts that list the tool surface:

- ``docs/TOOL_CATALOG.md``: every registry tool — name, config path,
  kind, range/enum/default, which presets set it — with the registry's
  own counts pinned;
- ``scripts/completions/caelestia-assist.bash``: a bash completion for
  the settings layer's flags, preset names, and tool names.

The committed files are the OUTPUT of this module; a test re-runs the
generator and asserts byte-identity (the gen_adapter --verify
discipline), so a registry change that outdates the catalog FAILS THE
BUILD instead of silently shipping stale docs. ``--verify`` exposes the
same check to CI and to contributors.

Pure generation: no I/O in the pure functions; the CLI writes only the
two declared paths (or verifies).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from . import presets as presets_mod
from .registry import GROUPS, TOOL_COUNT, TOOL_SPECS

__all__ = ["catalog_markdown", "completions_bash", "ARTIFACTS",
           "generate", "verify"]

# The committed artifacts, relative to the repo root (the CLI resolves
# the root as the parent of the assistant package directory).
ARTIFACTS: Tuple[Tuple[str, str], ...] = (
    ("docs/TOOL_CATALOG.md", "catalog_markdown"),
    ("scripts/completions/caelestia-assist.bash", "completions_bash"),
)

_SETTINGS_FLAGS = [
    "--apply", "--restore", "--file", "--json", "--list-tools", "--group",
    "--tool", "--call", "--explain", "--history", "--prefer", "--threeway",
    "--what-if", "--why-chain", "--counterfactual", "--accessibility-check",
    "--cvd", "--severity", "--recommend", "--rank", "--undo", "--undo-id",
    "--preset", "--list-presets", "--confirm", "--lint", "--audit-env",
    "--wallpaper-palette", "--wizard", "--answers", "--macro", "--macro-save",
    "--macro-list", "--macro-delete", "--from-id", "--profile",
    "--profile-save", "--also", "--profile-list", "--profile-show",
    "--profile-diff", "--profile-delete", "--profile-whatif", "--env-save",
    "--env-list", "--env-show", "--env-diff", "--env-restore",
    "--env-delete", "--env-export", "--env-import", "--to", "--as",
    "--monitor", "--monitors",
]


def _range_text(spec) -> str:
    if spec.enum:
        return "`" + " | ".join(str(v) for v in spec.enum) + "`"
    parts = []
    if spec.minimum is not None:
        parts.append(f"min {spec.minimum}")
    if spec.maximum is not None:
        parts.append(f"max {spec.maximum}")
    return ", ".join(parts) if parts else "—"


def _default_text(spec) -> str:
    if spec.default is not None:
        return f"`{spec.default}`"
    return "—"


def catalog_markdown() -> str:
    """The full tool catalog as markdown (pure; deterministic)."""
    preset_touch: Dict[str, List[str]] = {}
    for preset in presets_mod.presets():
        for call in preset["calls"]:
            preset_touch.setdefault(call[0], []).append(preset["name"])
    group_tools: Dict[str, List[Any]] = {}
    for spec in TOOL_SPECS:
        group_tools.setdefault(spec.group, []).append(spec)

    lines: List[str] = [
        "# Tool catalog",
        "",
        "<!-- GENERATED by assistant.settings.catalog — do not edit by hand.",
        "     Re-generate with `python3 -m assistant.settings --gen-catalog`",
        "     and verify with `--gen-catalog --verify`. -->",
        "",
        f"Registry version: generated from the caelestia-kde checkout this",
        f"assistant pins; **{TOOL_COUNT} tools** in {len(group_tools)} "
        f"groups, {len(presets_mod.presets())} presets.",
        "",
        "A tool is a validated setter for one shell.json path. Every value",
        "passes the tool's own validation before any plan exists; nothing",
        "here is ever executed by the assistant itself — suggested changes",
        "ride the preview -> consent -> applier gate.",
        "",
    ]
    for group in sorted(group_tools):
        lines.append(f"## {group} ({len(group_tools[group])})")
        lines.append("")
        lines.append("| tool | path | kind | range/enum | default | presets |")
        lines.append("|---|---|---|---|---|---|")
        for spec in sorted(group_tools[group], key=lambda s: s.name):
            presets = ", ".join(sorted(preset_touch.get(spec.name, [])))
            lines.append(
                f"| `{spec.name}` | `{spec.path}` | {spec.kind} | "
                f"{_range_text(spec)} | {_default_text(spec)} | "
                f"{presets or '—'} |")
        lines.append("")
    return "\n".join(lines) + "\n"


def completions_bash() -> str:
    """bash completion for the settings layer (pure; deterministic)."""
    words = " ".join(sorted(_SETTINGS_FLAGS))
    preset_words = " ".join(sorted(p["name"] for p in presets_mod.presets()))
    tool_words = " ".join(sorted(spec.name for spec in TOOL_SPECS))
    return (
        "# caelestia-assist settings — bash completion (GENERATED by\n"
        "# assistant.settings.catalog; verify with --gen-catalog --verify)\n"
        "# shellcheck shell=bash\n"
        "_caelestia_assist_settings() {\n"
        "  local cur prev\n"
        "  cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
        "  case \"$cur\" in\n"
        "    -*)\n"
        f"      COMPREPLY=( $(compgen -W \"{words}\" -- \"$cur\") ) ;;\n"
        "    *)\n"
        "      local prev2=\"${COMP_WORDS[COMP_CWORD-1]}\"\n"
        "      case \"$prev2\" in\n"
        "        --preset|--recommend|--tool|--explain)\n"
        f"          COMPREPLY=( $(compgen -W \"{tool_words}\" -- \"$cur\") ) ;;\n"
        "        --profile|--macro)\n"
        "          COMPREPLY=( ) ;;  # user-defined names: not enumerable\n"
        "        *)\n"
        f"          COMPREPLY=( $(compgen -W \"{preset_words}\" -- \"$cur\") ) ;;\n"
        "      esac ;;\n"
        "  esac\n"
        "}\n"
        "complete -F _caelestia_assist_settings -o default "
        "caelestia-assist\n"
        "complete -F _caelestia_assist_settings -o default "
        "python3-m-assistant.settings 2>/dev/null || true\n"
    )


def generate(root: Optional[Path] = None) -> Dict[str, str]:
    """Write the committed artifacts. Returns {path: bytes-written}."""
    root = root or _default_root()
    written: Dict[str, str] = {}
    for rel, fn_name in ARTIFACTS:
        content = globals()[fn_name]()
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written[rel] = str(path)
    return written


def verify(root: Optional[Path] = None) -> List[str]:
    """Byte-identity check of the committed artifacts against a fresh
    generation. Returns the list of mismatching paths (empty = all
    current)."""
    root = root or _default_root()
    problems: List[str] = []
    for rel, fn_name in ARTIFACTS:
        expected = globals()[fn_name]()
        path = root / rel
        try:
            actual = path.read_text(encoding="utf-8")
        except OSError:
            problems.append(f"{rel}: MISSING (run --gen-catalog)")
            continue
        if actual != expected:
            problems.append(f"{rel}: STALE (registry moved past the "
                            f"committed artifact; run --gen-catalog)")
    return problems


def _default_root() -> Path:
    return Path(__file__).resolve().parents[2]
